const provincesWithCities: { [key: string]: string[] } = {
    "Nanggroe Aceh Darussalam": ["Meulaboh", "Blangpidie", "Kota Jantho", "Calang", "Tapak Tuan", "Singkil", "Karang Baru", "Takengon", "Kutacane", "Idi Rayeuk", "Lhoksukon", "Simpang Tiga Redelong", "Bireuen", "Blang Kejeren", "Suka Makmue", "Sigli", "Meureudu", "Sinabang", "Banda Aceh", "Langsa", "Lhokseumawe", "Sabang", "Subulussalam"],
    "Sumatera Utara": [],
    "Sumatera Selatan": [],
    "Sumatera Barat": [],
    "Bengkulu": [],
    "Riau": [],
    "Kepulauan Riau": [],
    "Jambi": [],
    "Lampung": [],
    "Bangka Belitung": [],
    "Kalimantan Barat": [],
    "Kalimantan Timur": [],
    "Kalimantan Selatan": [],
    "Kalimantan Tengah": [],
    "Kalimantan Utara": [],
    "Banten": [],
    "DKI Jakarta": [],
    "Jawa Barat": ["Soreang", "Ngamprah", "Cikarang Pusat", "Cibinong", "Ciamis", "Cianjur", "Sumber", "Tarogong Kidul", "Indramayu", "Karawang Barat", "Kuningan", "Majalengka", "Parigi", "Purwakarta", "Subang", "Palabuhanratu", "Sumedang Utara", "Singaparna", "Bandung", "Banjar", "Bekasi", "Bogor", "Cimahi", "Cirebon", "Depok", "Sukabumi", "Tasikmalaya"],
    "Jawa Tengah": [],
    "Daerah Istimewa Yogyakarta": [],
    "Jawa Timur": [],
    "Bali": [],
    "Nusa Tenggara Timur": [],
    "Nusa Tenggara Barat": [],
    "Gorontalo": [],
    "Sulawesi Barat": [],
    "Sulawesi Tengah": [],
    "Sulawesi Utara": [],
    "Sulawesi Tenggara": [],
    "Sulawesi Selatan": [],
    "Maluku Utara": [],
    "Maluku": [],
    "Papua Barat": [],
    "Papua": [],
    "Papua Tengah": [],
    "Papua Pegunungan": [],
    "Papua Selatan": [],
    "Papua Barat Daya": []
  };
  